[RELAY_CHANNELS]
channel_1 = DUT_GND
channel_2 = DUT_VDD_2
channel_3 = USB_POWER
channel_4 = DUT_VDD_1
channel_5 = DUT_SIGNAL_1
channel_6 = DUT_SIGNAL_2
channel_7 = DUT_SIGNAL_3
channel_8 = DUT_SIGNAL_4

; ch1 = DUT_VDD_1
; ch2 = DUT_VDD_2
; 3 = USB_POWER
; 4 = DUT_GND
; 5 = DUT_SIGNAL_1
; 6 = DUT_SIGNAL_2
; 7 = DUT_SIGNAL_3
; 8 = DUT_SIGNAL_4


