[THEME]
# Available themes: darcula.json (dark), light.json (light blue)
theme_file = darcula.json

[PATHS]
# Base directory for all data output
data_dir = data

[AUTOCONNECT]
# 2=DMM
# 5=PS
# 6=FG
# 7=ATE
tab_1 = NO
tab_2 = NO
tab_3 = NO
tab_4 = NO
tab_5 = NO
tab_6 = YES
tab_7 = NO
tab_8 = NO
tab_9 = NO


[USB]
# Baud rate for USB serial communication
baud_rate = 9600

[Target]
power_type = 2
ps_channel = 1
debug_config = 1
vdds = 3.3
usb_relay = 0