[THEME]
# Available themes: darcula.json (dark), light.json (light blue)
theme_file = darcula.json

[AUTOCONNECT]
tab_1 = NO  # MAIN
tab_2 = NO  # DMM Control
tab_3 = NO  # XDS110 JTAG
tab_4 = YES # USB COMM
tab_5 = NO  # PS Control
tab_6 = NO  # FG Control
tab_7 = NO  # ATE
tab_8 = NO  # Logger
tab_9 = NO  # GRAPH


[USB]
# Baud rate for USB serial communication
baud_rate = 9600

[Target]
power_type = 2
ps_channel = 1
debug_config = 1
vdds = 3.3
usb_relay = 0